#ifndef DEVICE_DATA_H_
#define DEVICE_DATA_H_

#define OPENER_DEVICE_VENDOR_ID      55512
#define OPENER_DEVICE_TYPE           7
#define OPENER_DEVICE_PRODUCT_CODE   1
#define OPENER_DEVICE_MAJOR_REVISION 1
#define OPENER_DEVICE_MINOR_REVISION 0
#define OPENER_DEVICE_NAME           "QuinLEDPentaPlus"
#define OPENER_DEVICE_SERIAL_NUMBER  7792400897


#endif

